In [1]:
import torch
import torch.nn as nn
from torch.utils.data import TensorDataset, DataLoader, random_split
from UCroma import PretrainedCROMA
import copy

from CR_LO import Loader
from CR_FE import FExtractor
from TR import Trainer
from TE import Tester


sample_size = 120
batch_size = 16

Croma = PretrainedCROMA(pretrained_path='CR.pt', size='base', modality='both', image_resolution=sample_size)
num_features = Croma(SAR_images=torch.randn(1, 2, sample_size, sample_size), 
                     optical_images=torch.randn(1, 12, sample_size, sample_size))['joint_GAP'].shape[1]
head = nn.Sequential(nn.Linear(num_features, 1000), nn.ReLU(), nn.Linear(1000, 1000), nn.ReLU(), nn.Linear(1000, 2))

opt_root_dir = "/home/stagiaire/D/R/patchs/90"
sar_root_dir = "/home/stagiaire/D/R/patchs/90R"

num_cv = 5
num_folds = 5
metrics = [[] for _ in range(num_cv)]

for n in range(num_cv):
    processor = Loader(opt_root_dir=opt_root_dir, sar_root_dir=sar_root_dir, num_folds=num_folds)
    processor.load_data(sample_size=sample_size, batch_size=batch_size, data_seed=None, split_seed=None)
    loaders = processor.loaders
    
    floaders = []
    for loader in loaders:
        feature_extractor = FExtractor(dataloader=loader, use_8_bit=True)
        features, labels = feature_extractor.extract_features()
        dataset = TensorDataset(torch.from_numpy(features), torch.from_numpy(labels))
        floaders.append(DataLoader(dataset, batch_size=batch_size, shuffle=True))
        
    for i in range(num_folds):
        
        head_i = copy.deepcopy(head)
        
        train_loaders = [floaders[(j + i) % num_folds] for j in range(num_folds - 1)]
        test_loader = floaders[(i + num_folds - 1) % num_folds]
        
        for train_loader in train_loaders:
            trainer = Trainer(head_i, train_loader)
            trainer.train(num_epochs=100)
            
        tester = Tester(head_i, test_loader, processor.combined_dataset)
        tester.evaluate()
        
        metrics[n].append(tester.report)

/home/stagiaire/miniconda3/envs/croma/lib/python3.11/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: '/home/stagiaire/miniconda3/envs/croma/lib/python3.11/site-packages/torchvision/image.so: undefined symbol: _ZN5torch3jit17parseSchemaOrNameERKSs'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(


Initializing SAR encoder
Initializing optical encoder
Initializing joint SAR-optical encoder
Initializing SAR encoder
Initializing optical encoder
Initializing joint SAR-optical encoder


Extracting Features: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 12/12 [00:02<00:00,  5.44it/s]


Initializing SAR encoder
Initializing optical encoder
Initializing joint SAR-optical encoder


Extracting Features: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 12/12 [00:02<00:00,  5.55it/s]


Initializing SAR encoder
Initializing optical encoder
Initializing joint SAR-optical encoder


Extracting Features: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 12/12 [00:02<00:00,  5.45it/s]


Initializing SAR encoder
Initializing optical encoder
Initializing joint SAR-optical encoder


Extracting Features: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 12/12 [00:02<00:00,  5.40it/s]


Initializing SAR encoder
Initializing optical encoder
Initializing joint SAR-optical encoder


Training: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 100/100 [00:01<00:00, 83.50 epochs/s]



Jaccard index:  70.0%


                Predicted Class 0  Predicted Class 1
Actual Class 0                 83                 12
Actual Class 1                 18                 70


              precision    recall  f1-score   support

           0       0.82      0.87      0.85        95
           1       0.85      0.80      0.82        88

    accuracy                           0.84       183
   macro avg       0.84      0.83      0.84       183
weighted avg       0.84      0.84      0.84       183




Training: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 100/100 [00:01<00:00, 80.82 epochs/s]



Jaccard index:  70.4%


                Predicted Class 0  Predicted Class 1
Actual Class 0                 76                  8
Actual Class 1                 24                 76


              precision    recall  f1-score   support

           0       0.76      0.90      0.83        84
           1       0.90      0.76      0.83       100

    accuracy                           0.83       184
   macro avg       0.83      0.83      0.83       184
weighted avg       0.84      0.83      0.83       184




Training: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 100/100 [00:01<00:00, 83.64 epochs/s]



Jaccard index:  75.7%


                Predicted Class 0  Predicted Class 1
Actual Class 0                 81                 18
Actual Class 1                  7                 78


              precision    recall  f1-score   support

           0       0.92      0.82      0.87        99
           1       0.81      0.92      0.86        85

    accuracy                           0.86       184
   macro avg       0.87      0.87      0.86       184
weighted avg       0.87      0.86      0.86       184




Training: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 100/100 [00:00<00:00, 114.14 epochs/s]



Jaccard index:  73.9%


                Predicted Class 0  Predicted Class 1
Actual Class 0                 73                 10
Actual Class 1                 19                 82


              precision    recall  f1-score   support

           0       0.79      0.88      0.83        83
           1       0.89      0.81      0.85       101

    accuracy                           0.84       184
   macro avg       0.84      0.85      0.84       184
weighted avg       0.85      0.84      0.84       184




Training: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 100/100 [00:00<00:00, 115.29 epochs/s]



Jaccard index:  72.7%


                Predicted Class 0  Predicted Class 1
Actual Class 0                 73                 25
Actual Class 1                  5                 80


              precision    recall  f1-score   support

           0       0.94      0.74      0.83        98
           1       0.76      0.94      0.84        85

    accuracy                           0.84       183
   macro avg       0.85      0.84      0.84       183
weighted avg       0.86      0.84      0.84       183


Initializing SAR encoder
Initializing optical encoder
Initializing joint SAR-optical encoder


Extracting Features: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 12/12 [00:02<00:00,  5.40it/s]


Initializing SAR encoder
Initializing optical encoder
Initializing joint SAR-optical encoder


Extracting Features: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 12/12 [00:02<00:00,  5.61it/s]


Initializing SAR encoder
Initializing optical encoder
Initializing joint SAR-optical encoder


Extracting Features: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 12/12 [00:02<00:00,  5.64it/s]


Initializing SAR encoder
Initializing optical encoder
Initializing joint SAR-optical encoder


Extracting Features: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 12/12 [00:02<00:00,  5.66it/s]


Initializing SAR encoder
Initializing optical encoder
Initializing joint SAR-optical encoder


Training: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 100/100 [00:00<00:00, 112.53 epochs/s]



Jaccard index:  74.5%


                Predicted Class 0  Predicted Class 1
Actual Class 0                 85                  9
Actual Class 1                 16                 73


              precision    recall  f1-score   support

           0       0.84      0.90      0.87        94
           1       0.89      0.82      0.85        89

    accuracy                           0.86       183
   macro avg       0.87      0.86      0.86       183
weighted avg       0.87      0.86      0.86       183




Training: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 100/100 [00:00<00:00, 111.49 epochs/s]



Jaccard index:  77.6%


                Predicted Class 0  Predicted Class 1
Actual Class 0                 77                 17
Actual Class 1                  7                 83


              precision    recall  f1-score   support

           0       0.92      0.82      0.87        94
           1       0.83      0.92      0.87        90

    accuracy                           0.87       184
   macro avg       0.87      0.87      0.87       184
weighted avg       0.87      0.87      0.87       184




Training: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 100/100 [00:00<00:00, 118.54 epochs/s]



Jaccard index:  76.0%


                Predicted Class 0  Predicted Class 1
Actual Class 0                 80                 11
Actual Class 1                 14                 79


              precision    recall  f1-score   support

           0       0.85      0.88      0.86        91
           1       0.88      0.85      0.86        93

    accuracy                           0.86       184
   macro avg       0.86      0.86      0.86       184
weighted avg       0.86      0.86      0.86       184




Training: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 100/100 [00:00<00:00, 113.82 epochs/s]



Jaccard index:  77.8%


                Predicted Class 0  Predicted Class 1
Actual Class 0                 76                 17
Actual Class 1                  7                 84


              precision    recall  f1-score   support

           0       0.92      0.82      0.86        93
           1       0.83      0.92      0.88        91

    accuracy                           0.87       184
   macro avg       0.87      0.87      0.87       184
weighted avg       0.87      0.87      0.87       184




Training: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 100/100 [00:00<00:00, 114.42 epochs/s]



Jaccard index:  71.3%


                Predicted Class 0  Predicted Class 1
Actual Class 0                 75                 12
Actual Class 1                 19                 77


              precision    recall  f1-score   support

           0       0.80      0.86      0.83        87
           1       0.87      0.80      0.83        96

    accuracy                           0.83       183
   macro avg       0.83      0.83      0.83       183
weighted avg       0.83      0.83      0.83       183


Initializing SAR encoder
Initializing optical encoder
Initializing joint SAR-optical encoder


Extracting Features: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 12/12 [00:02<00:00,  5.54it/s]


Initializing SAR encoder
Initializing optical encoder
Initializing joint SAR-optical encoder


Extracting Features: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 12/12 [00:02<00:00,  5.57it/s]


Initializing SAR encoder
Initializing optical encoder
Initializing joint SAR-optical encoder


Extracting Features: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 12/12 [00:02<00:00,  5.62it/s]


Initializing SAR encoder
Initializing optical encoder
Initializing joint SAR-optical encoder


Extracting Features: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 12/12 [00:02<00:00,  5.67it/s]


Initializing SAR encoder
Initializing optical encoder
Initializing joint SAR-optical encoder


Training: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 100/100 [00:01<00:00, 85.17 epochs/s]



Jaccard index:  67.6%


                Predicted Class 0  Predicted Class 1
Actual Class 0                 75                 26
Actual Class 1                  9                 73


              precision    recall  f1-score   support

           0       0.89      0.74      0.81       101
           1       0.74      0.89      0.81        82

    accuracy                           0.81       183
   macro avg       0.82      0.82      0.81       183
weighted avg       0.82      0.81      0.81       183




Training: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 100/100 [00:01<00:00, 86.31 epochs/s]



Jaccard index:  63.6%


                Predicted Class 0  Predicted Class 1
Actual Class 0                 74                 14
Actual Class 1                 26                 70


              precision    recall  f1-score   support

           0       0.74      0.84      0.79        88
           1       0.83      0.73      0.78        96

    accuracy                           0.78       184
   macro avg       0.79      0.79      0.78       184
weighted avg       0.79      0.78      0.78       184




Training: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 100/100 [00:01<00:00, 91.61 epochs/s]



Jaccard index:  68.8%


                Predicted Class 0  Predicted Class 1
Actual Class 0                 75                 21
Actual Class 1                 13                 75


              precision    recall  f1-score   support

           0       0.85      0.78      0.82        96
           1       0.78      0.85      0.82        88

    accuracy                           0.82       184
   macro avg       0.82      0.82      0.82       184
weighted avg       0.82      0.82      0.82       184




Training: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 100/100 [00:01<00:00, 92.91 epochs/s]



Jaccard index:  75.9%


                Predicted Class 0  Predicted Class 1
Actual Class 0                 76                 12
Actual Class 1                 14                 82


              precision    recall  f1-score   support

           0       0.84      0.86      0.85        88
           1       0.87      0.85      0.86        96

    accuracy                           0.86       184
   macro avg       0.86      0.86      0.86       184
weighted avg       0.86      0.86      0.86       184




Training: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 100/100 [00:01<00:00, 87.33 epochs/s]



Jaccard index:  70.0%


                Predicted Class 0  Predicted Class 1
Actual Class 0                 73                 13
Actual Class 1                 20                 77


              precision    recall  f1-score   support

           0       0.78      0.85      0.82        86
           1       0.86      0.79      0.82        97

    accuracy                           0.82       183
   macro avg       0.82      0.82      0.82       183
weighted avg       0.82      0.82      0.82       183


Initializing SAR encoder
Initializing optical encoder
Initializing joint SAR-optical encoder


Extracting Features: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 12/12 [00:02<00:00,  5.53it/s]


Initializing SAR encoder
Initializing optical encoder
Initializing joint SAR-optical encoder


Extracting Features: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 12/12 [00:02<00:00,  5.54it/s]


Initializing SAR encoder
Initializing optical encoder
Initializing joint SAR-optical encoder


Extracting Features: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 12/12 [00:02<00:00,  5.54it/s]


Initializing SAR encoder
Initializing optical encoder
Initializing joint SAR-optical encoder


Extracting Features: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 12/12 [00:02<00:00,  5.62it/s]


Initializing SAR encoder
Initializing optical encoder
Initializing joint SAR-optical encoder


Training: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 100/100 [00:00<00:00, 115.85 epochs/s]



Jaccard index:  68.5%


                Predicted Class 0  Predicted Class 1
Actual Class 0                 72                 16
Actual Class 1                 19                 76


              precision    recall  f1-score   support

           0       0.79      0.82      0.80        88
           1       0.83      0.80      0.81        95

    accuracy                           0.81       183
   macro avg       0.81      0.81      0.81       183
weighted avg       0.81      0.81      0.81       183




Training: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 100/100 [00:01<00:00, 96.98 epochs/s]



Jaccard index:  74.3%


                Predicted Class 0  Predicted Class 1
Actual Class 0                 75                 13
Actual Class 1                 15                 81


              precision    recall  f1-score   support

           0       0.83      0.85      0.84        88
           1       0.86      0.84      0.85        96

    accuracy                           0.85       184
   macro avg       0.85      0.85      0.85       184
weighted avg       0.85      0.85      0.85       184




Training: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 100/100 [00:01<00:00, 84.08 epochs/s]



Jaccard index:  76.6%


                Predicted Class 0  Predicted Class 1
Actual Class 0                 73                 19
Actual Class 1                  7                 85


              precision    recall  f1-score   support

           0       0.91      0.79      0.85        92
           1       0.82      0.92      0.87        92

    accuracy                           0.86       184
   macro avg       0.86      0.86      0.86       184
weighted avg       0.86      0.86      0.86       184




Training: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 100/100 [00:01<00:00, 85.78 epochs/s]



Jaccard index:  67.6%


                Predicted Class 0  Predicted Class 1
Actual Class 0                 79                 19
Actual Class 1                 15                 71


              precision    recall  f1-score   support

           0       0.84      0.81      0.82        98
           1       0.79      0.83      0.81        86

    accuracy                           0.82       184
   macro avg       0.81      0.82      0.81       184
weighted avg       0.82      0.82      0.82       184




Training: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 100/100 [00:01<00:00, 92.21 epochs/s]



Jaccard index:  75.5%


                Predicted Class 0  Predicted Class 1
Actual Class 0                 85                  8
Actual Class 1                 16                 74


              precision    recall  f1-score   support

           0       0.84      0.91      0.88        93
           1       0.90      0.82      0.86        90

    accuracy                           0.87       183
   macro avg       0.87      0.87      0.87       183
weighted avg       0.87      0.87      0.87       183


Initializing SAR encoder
Initializing optical encoder
Initializing joint SAR-optical encoder


Extracting Features: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 12/12 [00:02<00:00,  5.53it/s]


Initializing SAR encoder
Initializing optical encoder
Initializing joint SAR-optical encoder


Extracting Features: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 12/12 [00:02<00:00,  5.56it/s]


Initializing SAR encoder
Initializing optical encoder
Initializing joint SAR-optical encoder


Extracting Features: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 12/12 [00:02<00:00,  5.60it/s]


Initializing SAR encoder
Initializing optical encoder
Initializing joint SAR-optical encoder


Extracting Features: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 12/12 [00:02<00:00,  5.60it/s]


Initializing SAR encoder
Initializing optical encoder
Initializing joint SAR-optical encoder


Training: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 100/100 [00:01<00:00, 92.38 epochs/s]



Jaccard index:  72.8%


                Predicted Class 0  Predicted Class 1
Actual Class 0                 80                 14
Actual Class 1                 14                 75


              precision    recall  f1-score   support

           0       0.85      0.85      0.85        94
           1       0.84      0.84      0.84        89

    accuracy                           0.85       183
   macro avg       0.85      0.85      0.85       183
weighted avg       0.85      0.85      0.85       183




Training: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 100/100 [00:00<00:00, 113.69 epochs/s]



Jaccard index:  72.6%


                Predicted Class 0  Predicted Class 1
Actual Class 0                 71                  6
Actual Class 1                 25                 82


              precision    recall  f1-score   support

           0       0.74      0.92      0.82        77
           1       0.93      0.77      0.84       107

    accuracy                           0.83       184
   macro avg       0.84      0.84      0.83       184
weighted avg       0.85      0.83      0.83       184




Training: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 100/100 [00:01<00:00, 94.79 epochs/s]



Jaccard index:  81.8%


                Predicted Class 0  Predicted Class 1
Actual Class 0                 74                 18
Actual Class 1                  2                 90


              precision    recall  f1-score   support

           0       0.97      0.80      0.88        92
           1       0.83      0.98      0.90        92

    accuracy                           0.89       184
   macro avg       0.90      0.89      0.89       184
weighted avg       0.90      0.89      0.89       184




Training: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 100/100 [00:01<00:00, 88.44 epochs/s]



Jaccard index:  70.9%


                Predicted Class 0  Predicted Class 1
Actual Class 0                 74                 18
Actual Class 1                 14                 78


              precision    recall  f1-score   support

           0       0.84      0.80      0.82        92
           1       0.81      0.85      0.83        92

    accuracy                           0.83       184
   macro avg       0.83      0.83      0.83       184
weighted avg       0.83      0.83      0.83       184




Training: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 100/100 [00:01<00:00, 89.36 epochs/s]


Jaccard index:  66.3%


                Predicted Class 0  Predicted Class 1
Actual Class 0                 79                 25
Actual Class 1                 10                 69


              precision    recall  f1-score   support

           0       0.89      0.76      0.82       104
           1       0.73      0.87      0.80        79

    accuracy                           0.81       183
   macro avg       0.81      0.82      0.81       183
weighted avg       0.82      0.81      0.81       183




In [2]:
from R import RGenerator
    
new_metrics = []
for l in metrics:
    new_metrics.extend(l)

reporter = RGenerator(new_metrics).report()

Precision (mean, stdev): 84%, 5%
Recall (mean, stdev): 85%, 6%
F1-score (mean, stdev): 84%, 3%
IoU (mean, stdev): 73%, 4%

[[77. 15.]
 [14. 78.]]

[[4. 5.]
 [6. 5.]]



In [3]:
for l in metrics:
    reporter = RGenerator(l).report()

Precision (mean, stdev): 84%, 5%
Recall (mean, stdev): 85%, 7%
F1-score (mean, stdev): 84%, 1%
IoU (mean, stdev): 73%, 2%

[[77. 15.]
 [15. 77.]]

[[4. 6.]
 [7. 4.]]

Precision (mean, stdev): 86%, 3%
Recall (mean, stdev): 86%, 5%
F1-score (mean, stdev): 86%, 2%
IoU (mean, stdev): 75%, 2%

[[79. 13.]
 [13. 79.]]

[[4. 3.]
 [5. 4.]]

Precision (mean, stdev): 82%, 5%
Recall (mean, stdev): 82%, 6%
F1-score (mean, stdev): 82%, 3%
IoU (mean, stdev): 69%, 4%

[[75. 17.]
 [16. 75.]]

[[1. 5.]
 [6. 4.]]

Precision (mean, stdev): 84%, 4%
Recall (mean, stdev): 84%, 4%
F1-score (mean, stdev): 84%, 3%
IoU (mean, stdev): 72%, 4%

[[77. 15.]
 [14. 77.]]

[[5. 4.]
 [4. 5.]]

Precision (mean, stdev): 83%, 6%
Recall (mean, stdev): 86%, 7%
F1-score (mean, stdev): 84%, 3%
IoU (mean, stdev): 73%, 5%

[[76. 16.]
 [13. 79.]]

[[3. 6.]
 [7. 7.]]

